### ISSUE TITLE
[BUG] Failed to load model

### ISSUE THREAD

**Issue by itsjpavank** [microsoft/ai-dev-gallery#411]
**Describe the bug**

**To Reproduce**
Transcribe audio or video

**Expected behavior**
The model should load and I should be able to transcribe audio/video

**Screenshots**
![Image](https://github.com/user-attachments/assets/216e6aae-285c-4fb7-ba66-5ad84245e586)

**Please complete the following information:**
Version 0.4.5.0

**Additional context**
Type: OnnxRuntimeException
Message: [ErrorCode:RuntimeException] Exception during initialization: D:\a\_work\1\s\WCRforIntel\win-onnxruntime\onnxruntime\core\providers\openvino\ov_interface.cc:81 class std::shared_ptr<class ov::Model> __cdecl onnxruntime::openvino_ep::OVCore::ReadModel(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&,const class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &) [OpenVINO-EP] [OpenVINO-EP] Exception while Reading network: Check 'onnx_node.get_outputs_size() <= outputs_size' failed at src\frontends\onnx\frontend\src\core\graph.cpp:399:
FrontEnd API failed with GeneralFailure:
Expected output number of SkipLayerNormalization node is 4 while the implementation provides 1 outputs

StackTrace:    at Microsoft.ML.OnnxRuntime.InferenceSession.Init(String modelPath, SessionOptions options, PrePackedWeightsContainer prepackedWeightsContainer)
   at AIDevGallery.Samples.SharedCode.WhisperWrapper.CreateAsync(String modelPath, Nullable`1 policy, String device, Boolean compileModel)
   at AIDevGallery.Samples.OpenSourceModels.Whisper.WhisperAudioTranscription.LoadModelAsync(SampleNavigationParameters sampleParams)

[Failed to load model..txt](https://github.com/user-attachments/files/21356941/Failed.to.load.model.txt)

**Comment by nmetulev** [comment]
Hi @itsjpavank, can you share what device you are using?

Also, are you able to manually select an EP in this view? If so, what EPs do you see?

<img width="521" height="347" alt="Image" src="https://github.com/user-attachments/assets/05bc961d-2347-4023-8716-7fe3d458090d" />

**Comment by AndrewKeepCoding** [comment]
@nmetulev This is reproducible on my end and the only available EP is **CPU (CPU)**, exactly as shown in the screenshot you shared.

**Comment by AndrewKeepCoding** [comment]
I took a quick look at this and the exception is thrown trying to instantiate `InferenceSession`:

**WhisperWrapper.cs**
```cs
public static async Task<WhisperWrapper> CreateAsync(string modelPath, ExecutionProviderDevicePolicy? policy, string? device, bool compileModel)
{
    ...

    if (policy != null)
    {
        sessionOptions.SetEpSelectionPolicy(policy.Value);
    }
    else if (device != null)
    {
        sessionOptions.AppendExecutionProviderFromEpName(device);

        if (compileModel)
        {
            modelPath = sessionOptions.GetCompiledModel(modelPath, device) ?? modelPath;
        }
    }

    InferenceSession inferenceSession = new InferenceSession(modelPath, sessionOptions);
    var whisper = new WhisperWrapper(inferenceSession);
    return whisper;    
}
```

I'm not sure why but after removing this line the exception is not thrown.

```cs
//sessionOptions.SetEpSelectionPolicy(policy.Value);
```

@nmetulev  Any tips?

**Comment by Panepo** [comment]
Any tips about this ? The app version v0.5.3.0 also has the same problem on my computer.

**Comment by wang563681252** [comment]
Fixed, PR: https://github.com/microsoft/ai-dev-gallery/pull/480

**Comment by Panepo** [comment]
Hi, @wang563681252 

My app version v0.5.5.0 still have the same problem on my computer. I re-download the whisper models again but still pops up failed to load model window.
